### ISSUE TITLE
About training process status

### ISSUE THREAD

**Issue by raikarsagar** [facebookresearch/svoice#21]
Hi, I have preprocessed the data in required format and started training, But there is no live update on number of iterations/ loss. How do we check it in hydra?

**Comment by adiyoss** [comment]
Hi @raikarsagar,
You should see the log outputs (iterations, loss values, etc.) in the standard output. Maybe the reason you do not see it is due to long training time? 
You can control the number of outputs per epoch using the `num_prints` parameter. For example: 
'python train dset=<your dataset> num_prints=1000` this will generate 1000 prints per epoch to the standard output.
