### ISSUE TITLE
How to use MUSDB to get the experimental results of the 3.4 Music Source Separation section in paper ?

### ISSUE THREAD

**Issue by shuxinli6176** [facebookresearch/svoice#27]

**Comment by adiyoss** [comment]
Hi @shuxinli6176,
We did not uploaded the music source separation recipe since it is not the main focus of the paper. But you implement if easily. You should change the separation model in: `https://github.com/facebookresearch/demucs` to svoice (the one we are using). Next, you should modify the number of outputs to match the number of sources you would like to separate, in the case of MUSDB it would be four, iirc.

**Comment by shuxinli6176** [comment]
Thank you for the response, I'll follow your advice.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/svoice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/svoice] How to use MUSDB to get the experimental results of the 3.4 Music Source Separation section in paper ? (#27)





 
Hi @shuxinli6176,
 We did not uploaded the music source separation recipe since it is not the main focus of the paper. But you implement if easily. You should change the separation model in: https://github.com/facebookresearch/demucs to svoice (the one we are using). Next, you should modify the number of outputs to match the number of sources you would like to separate, in the case of MUSDB it would be four, iirc.

**Comment by adiyoss** [comment]
Closing the issue for now. Feel free to reopen it once you have interesting findings :)
