### ISSUE TITLE
How to use svoice to do music separation?

### ISSUE THREAD

**Issue by ShiZiqiang** [facebookresearch/svoice#6]
Hi!

svoice is such an impressive work. Thanks for opensource it. 
Thank you and best regards.

**Comment by enk100** [comment]
Please have a look in the model description for music separation. You need to change the vanilla svoice model in order to get the results in the paper. Please take a look at page 7 in the paper - https://arxiv.org/pdf/2003.01531.pdf
For example - you need to remove the PIL loss, change the loss to L1 and so on.

The svoice model that published in this repo is for speech sepration.

**Comment by ShiZiqiang** [comment]
Thank you, Dr. Nachmani.
